name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - 1.3.x

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged
      # https://github.com/release-drafter/release-drafter/releases
      # v5.21.1
      - uses: release-drafter/release-drafter@6df64e4ba4842c203c604c1f45246c5863410adb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
